image: node:14.17.1

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - apt-get update && apt-get install -y rsync
            - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
            - cd $BITBUCKET_CLONE_DIR
            - npm install
            - CI='' npm run build
            - CI='' npm run build-storybook
            - rsync -r -v -e ssh . $SSH_SERVER_USER@$SSH_SERVER_IP:~/traxnyc-frontend --delete-before --exclude '.git' --exclude 'node_modules'